### ISSUE TITLE
frequent Rock Exception notifications

### ISSUE THREAD

**Issue by CBC17044** [NewSpring/Rock-Plugins#206]
An exception has occurred. Details of this error can be found below:        
An error occurred on the Rock Attended Check-in site on page:        https://____________________/attendedcheckin/confirm      
 NullReferenceException  in App_Web_2gwcbi2q       
Message       Object reference not set to an instance of an object.      
Stack Trace       
at  RockWeb.Plugins.cc_newspring.AttendedCheckin.Confirm.gPersonList_Delete(Object sender, RowEventArgs e) in g:\pleskvhosts\ ________________\httpdocs\Plugins\cc_newspring\AttendedCheckin\Confirm.ascx.cs:line 340
at Rock.Web.UI.Controls.DeleteField.OnClick(RowEventArgs e)
at Rock.Web.UI.Controls.DeleteField.deleteFieldTemplate_LinkButtonClick(Object sender, RowEventArgs e)
at Rock.Web.UI.Controls.DeleteFieldTemplate.lbDelete_Click(Object sender, EventArgs e)
at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by CBC17044** [comment]
We received 14 of these notifications over the course of about 30min. Checkin was slow and/or unresponsive. We were using the desktop app.

**Comment by CBC17044** [comment]
I believe I have posted this in the wrong area... sorry.
