### ISSUE TITLE
Check-In: Editing check in to nothing causes problems

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#69]
When you edit a check-in, delete whatever the assignment was, then click the right arrow to get back to the summary page, the buttons for that person stop working, you also get the following error when you click edit

HttpUnhandledException in System.Web

Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.

Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_checkinpark_layouts_checkin_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\26676eb7\92c7e946\App_Web_o1r1qxgd.0.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

-NullReferenceException in App_Web_s054frkw

Message
Object reference not set to an instance of an object.

Stack Trace
at cc.newspring.AttendedCheckin.ActivitySelect.BindGroupTypes(List`1 groupTypes) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckIn\ActivitySelect.ascx.cs:line 673
at cc.newspring.AttendedCheckin.ActivitySelect.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckIn\ActivitySelect.ascx.cs:line 138
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at System.Web.UI.ControlCollection.Add(Control child)
at Rock.Web.UI.RockBlockWrapper.CreateChildControls() in c:\Users\ndsev\Desktop\Rock\Rock\Web\UI\RockBlockWrapper.cs:line 77
at System.Web.UI.Control.EnsureChildControls()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Control.PreRenderRecursiveInternal()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by FrankGrand** [comment]
If for some reason the assignment starts out as blank, you can't delete it:
http://goo.gl/2nkR0e
